// <auto-generated />
namespace PixelEngine.Demo;

internal static partial class NoitaPixelSceneCatalog
{
    private static readonly NoitaPixelSceneMarkerDefinition[] MarkerValues =
    [
        new(0, 251, 230, 9977L, -794L, "ff905ecc", "spawn_boss_limbs_trigger", "data/scripts/biomes/pyramid.lua"),
        new(1, 20, 41, 163L, 5153L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(1, 68, 41, 211L, 5153L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(1, 20, 55, 163L, 5167L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(1, 68, 55, 211L, 5167L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(2, 73, 66, 1537L, 6042L, "ff4cacab", "spawn_forge_check", "data/scripts/biomes/snowcastle.lua"),
        new(3, 20, 41, 163L, 8745L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(3, 68, 41, 211L, 8745L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(3, 20, 55, 163L, 8759L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(3, 68, 55, 211L, 8759L, "ffc78f20", "spawn_barricade", "data/scripts/biomes/robobase.lua|data/scripts/biomes/snowcastle.lua|data/scripts/biomes/vault_frozen.lua|data/scripts/biomes/vault.lua"),
        new(6, 41, 148, 41L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(6, 78, 148, 78L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(6, 114, 148, 114L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(6, 149, 148, 149L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(6, 184, 148, 184L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(6, 215, 148, 215L, 24724L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 41, 148, 41L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 78, 148, 78L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 114, 148, 114L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 149, 148, 149L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 184, 148, 184L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(7, 215, 148, 215L, -13806L, "ffbe704d", "spawn_specialshop", "data/scripts/biomes/the_end.lua"),
        new(8, 255, 248, 9471L, 4344L, "ffd0d0b4", "spawn_treasure", "data/scripts/biomes/hills.lua|data/scripts/biomes/winter.lua"),
        new(9, 148, 21, -12452L, 161L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/fishing_hut.png"),
        new(9, 171, 21, -12429L, 161L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/fishing_hut.png"),
        new(16, 252, 22, -12351L, 348L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker.png"),
        new(16, 215, 24, -12388L, 350L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker.png"),
        new(16, 173, 26, -12430L, 352L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker.png"),
        new(16, 120, 28, -12483L, 354L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker.png"),
        new(16, 62, 31, -12541L, 357L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker.png"),
        new(16, 239, 61, -12364L, 387L, "ff667600", "spawn_teleport_back", "data/scripts/biomes/lake.lua"),
        new(16, 95, 83, -12508L, 409L, "ffb27600", "spawn_bunker", "data/scripts/biomes/lake.lua"),
        new(16, 44, 89, -12559L, 415L, "ff390000", "spawn_alchemist", "data/scripts/biomes/lake.lua"),
        new(17, 252, 22, -12701L, 562L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker2.png"),
        new(17, 215, 24, -12738L, 564L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker2.png"),
        new(17, 173, 26, -12780L, 566L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker2.png"),
        new(17, 120, 28, -12833L, 568L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker2.png"),
        new(17, 62, 31, -12891L, 571L, "ffffff00", "builtin-or-unresolved:ffffff00", "data/biome_impl/bunker2.png"),
        new(17, 239, 61, -12714L, 601L, "ff667600", "spawn_teleport_back", "data/scripts/biomes/lake.lua"),
        new(17, 95, 83, -12858L, 623L, "ffb2a700", "spawn_bunker2", "data/scripts/biomes/lake.lua"),
        new(19, 58, 0, -14001L, -2851L, "ff5078c8", "spawn_rainbow_card", "data/scripts/biomes/lake.lua"),
        new(20, 213, 11, -12187L, -389L, "ff235a15", "spawn_music_machine", "data/scripts/biomes/hills.lua|data/scripts/biomes/lake.lua|data/scripts/biomes/winter.lua"),
        new(29, 87, 55, 9087L, -1845L, "ff616602", "spawn_huussi_checker", "data/scripts/biomes/desert.lua"),
    ];

    internal static ReadOnlySpan<NoitaPixelSceneMarkerDefinition> Markers => MarkerValues;
}
