using System.Text.Json.Serialization;

namespace PixelEngine.Editor.Automation.Protocol;

/// <summary>
/// automation wire/discovery 的 source-generated JSON metadata。
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Metadata,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    UseStringEnumConverter = true)]
[JsonSerializable(typeof(AutomationEnvelope))]
[JsonSerializable(typeof(AutomationError))]
[JsonSerializable(typeof(AutomationHelloRequest))]
[JsonSerializable(typeof(AutomationHelloChallenge))]
[JsonSerializable(typeof(AutomationAuthenticateRequest))]
[JsonSerializable(typeof(AutomationSessionInfo))]
[JsonSerializable(typeof(AutomationCancelRequest))]
[JsonSerializable(typeof(AutomationInstanceDescriptor))]
[JsonSerializable(typeof(AutomationEndpointDescriptor))]
[JsonSerializable(typeof(AutomationProjectSummary))]
[JsonSerializable(typeof(AutomationPingResponse))]
[JsonSerializable(typeof(AutomationProtocolVersion[]))]
[JsonSerializable(typeof(AutomationRevisionPrecondition))]
[JsonSerializable(typeof(AutomationExpectedResourceRevision))]
[JsonSerializable(typeof(AutomationRevisionSnapshot))]
[JsonSerializable(typeof(AutomationResourceRevision))]
[JsonSerializable(typeof(AutomationRevisionConflictDetails))]
[JsonSerializable(typeof(AutomationResourceRevisionConflict))]
[JsonSerializable(typeof(AutomationArtifactReference))]
[JsonSerializable(typeof(AutomationTransactionBeginRequest))]
[JsonSerializable(typeof(AutomationTransactionRequest))]
[JsonSerializable(typeof(AutomationTransactionInfo))]
[JsonSerializable(typeof(AutomationTransactionStagedOperationInfo))]
[JsonSerializable(typeof(AutomationTransactionOperationResult))]
[JsonSerializable(typeof(AutomationTransactionCommitResult))]
[JsonSerializable(typeof(AutomationTransactionFailureDetails))]
[JsonSerializable(typeof(AutomationEventRecord))]
[JsonSerializable(typeof(AutomationEventSubscribeRequest))]
[JsonSerializable(typeof(AutomationSubscriptionInfo))]
[JsonSerializable(typeof(AutomationEventAckRequest))]
[JsonSerializable(typeof(AutomationEventSubscriptionRequest))]
[JsonSerializable(typeof(AutomationEventResyncDetails))]
[JsonSerializable(typeof(AutomationStateChangedEvent))]
[JsonSerializable(typeof(AutomationFilterClause))]
[JsonSerializable(typeof(AutomationQueryFilter))]
[JsonSerializable(typeof(AutomationSortClause))]
[JsonSerializable(typeof(AutomationPageRequest))]
[JsonSerializable(typeof(AutomationPageInfo))]
[JsonSerializable(typeof(AutomationCapabilityDescriptor))]
[JsonSerializable(typeof(AutomationCapabilityDescriptor[]))]
[JsonSerializable(typeof(AutomationCapabilityListResponse))]
[JsonSerializable(typeof(AutomationWorkspaceSnapshot))]
[JsonSerializable(typeof(AutomationCommandResult))]
[JsonSerializable(typeof(AutomationWindowSnapshot))]
[JsonSerializable(typeof(AutomationWindowResizeRequest))]
[JsonSerializable(typeof(AutomationWindowSetRequest))]
[JsonSerializable(typeof(AutomationPanelInfo))]
[JsonSerializable(typeof(AutomationPanelInfo[]))]
[JsonSerializable(typeof(AutomationPanelListResponse))]
[JsonSerializable(typeof(AutomationPanelSetRequest))]
[JsonSerializable(typeof(AutomationPanelDockRequest))]
[JsonSerializable(typeof(AutomationPanelLayoutEntry))]
[JsonSerializable(typeof(AutomationPanelLayoutEntry[]))]
[JsonSerializable(typeof(AutomationDockLayoutSnapshot))]
[JsonSerializable(typeof(AutomationDockLayoutSetRequest))]
[JsonSerializable(typeof(AutomationSceneSnapshot))]
[JsonSerializable(typeof(AutomationScenePathRequest))]
[JsonSerializable(typeof(AutomationSceneSaveAsRequest))]
[JsonSerializable(typeof(AutomationTransitionResolveRequest))]
[JsonSerializable(typeof(AutomationTransitionResult))]
[JsonSerializable(typeof(AutomationHierarchyItem))]
[JsonSerializable(typeof(AutomationHierarchyItem[]))]
[JsonSerializable(typeof(AutomationHierarchyListResponse))]
[JsonSerializable(typeof(AutomationGameObjectRequest))]
[JsonSerializable(typeof(AutomationInspectorGetRequest))]
[JsonSerializable(typeof(AutomationTransformValue))]
[JsonSerializable(typeof(AutomationInspectorField))]
[JsonSerializable(typeof(AutomationInspectorField[]))]
[JsonSerializable(typeof(AutomationComponentSnapshot))]
[JsonSerializable(typeof(AutomationComponentSnapshot[]))]
[JsonSerializable(typeof(AutomationWebCanvasValue))]
[JsonSerializable(typeof(AutomationWebCanvasSnapshot))]
[JsonSerializable(typeof(AutomationCanvasScalerValue))]
[JsonSerializable(typeof(AutomationBuiltInCanvasSetRequest))]
[JsonSerializable(typeof(AutomationCanvasPrimarySetRequest))]
[JsonSerializable(typeof(AutomationHistorySnapshot))]
[JsonSerializable(typeof(AutomationPrefabCreateRequest))]
[JsonSerializable(typeof(AutomationPrefabCreateResult))]
[JsonSerializable(typeof(AutomationPrefabInstantiateRequest))]
[JsonSerializable(typeof(AutomationGameObjectSnapshot))]
[JsonSerializable(typeof(AutomationSelectionSetRequest))]
[JsonSerializable(typeof(AutomationSelectionSnapshot))]
[JsonSerializable(typeof(AutomationGameObjectCreateRequest))]
[JsonSerializable(typeof(AutomationGameObjectRenameRequest))]
[JsonSerializable(typeof(AutomationGameObjectBoolRequest))]
[JsonSerializable(typeof(AutomationBoolValueRequest))]
[JsonSerializable(typeof(AutomationGameObjectReparentRequest))]
[JsonSerializable(typeof(AutomationTransformSetRequest))]
[JsonSerializable(typeof(AutomationComponentAddRequest))]
[JsonSerializable(typeof(AutomationComponentRemoveRequest))]
[JsonSerializable(typeof(AutomationComponentEnabledSetRequest))]
[JsonSerializable(typeof(AutomationComponentMoveRequest))]
[JsonSerializable(typeof(AutomationComponentFieldSetRequest))]
[JsonSerializable(typeof(AutomationBrushSettings))]
[JsonSerializable(typeof(AutomationSceneToolSnapshot))]
[JsonSerializable(typeof(AutomationSceneToolSetRequest))]
[JsonSerializable(typeof(AutomationSceneFrameRequest))]
[JsonSerializable(typeof(AutomationBrushApplyRequest))]
[JsonSerializable(typeof(AutomationBrushApplyResult))]
[JsonSerializable(typeof(AutomationWorldPoint))]
[JsonSerializable(typeof(AutomationWorldPoint[]))]
[JsonSerializable(typeof(AutomationBrushStrokeRequest))]
[JsonSerializable(typeof(AutomationBrushStrokeResult))]
[JsonSerializable(typeof(string[]))]
public sealed partial class AutomationJsonContext : JsonSerializerContext;
