[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $DataRoot,

    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),

    [string] $OutputRoot = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\maps\noita\global-scenes'),

    [string] $GeneratedCodePath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaPixelSceneVisuals.Generated.cs'),

    [string] $ProvenancePath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\maps\noita\global-scenes\provenance.json')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8NoBom = [Text.UTF8Encoding]::new($false)
$resolvedDataRoot = (Resolve-Path -LiteralPath $DataRoot).Path
$catalog = Get-Content -Raw -LiteralPath $CatalogPath | ConvertFrom-Json -Depth 30
$resolvedOutputRoot = [IO.Path]::GetFullPath($OutputRoot)
[IO.Directory]::CreateDirectory($resolvedOutputRoot) | Out-Null

function Get-Sha256([string] $Path) {
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Add-Visual($Scene, [int] $Ordinal, [string] $Kind, [Collections.Generic.List[object]] $Destination) {
    $asset = $Scene.assets.PSObject.Properties[$Kind].Value
    if ($null -eq $asset) { return }
    $sourcePath = [string]$asset.path
    $sourceFile = Join-Path $resolvedDataRoot $sourcePath.Substring(5)
    $sourceSha256 = Get-Sha256 $sourceFile
    if (-not [string]::Equals($sourceSha256, [string]$asset.sha256, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Source hash mismatch for '$sourcePath'."
    }

    $fileName = '{0:d2}-{1}.png' -f $Ordinal, $Kind
    $outputFile = Join-Path $resolvedOutputRoot $fileName
    Copy-Item -LiteralPath $sourceFile -Destination $outputFile -Force
    $outputSha256 = Get-Sha256 $outputFile
    if (-not [string]::Equals($sourceSha256, $outputSha256, [StringComparison]::Ordinal)) {
        throw "Copied visual hash mismatch for '$sourcePath'."
    }

    $Destination.Add([ordered]@{
        ordinal = $Ordinal
        kind = $Kind
        sourcePath = $sourcePath
        sourceSha256 = $sourceSha256
        contentPath = "maps/noita/global-scenes/$fileName"
        contentSha256 = $outputSha256
        worldX = [int]$Scene.pos_x
        worldY = [int]$Scene.pos_y
        width = [int]$asset.width
        height = [int]$asset.height
    })
}

$visuals = [Collections.Generic.List[object]]::new()
$scenes = @($catalog.globalPixelScenes.bufferedScenes)
for ($i = 0; $i -lt $scenes.Count; $i++) {
    Add-Visual $scenes[$i] $i 'background' $visuals
}
for ($i = 0; $i -lt $scenes.Count; $i++) {
    Add-Visual $scenes[$i] $i 'colors' $visuals
}

$provenance = [ordered]@{
    schemaVersion = 1
    referenceBuildId = [string]$catalog.reference.steamBuildId
    referenceVersionHash = [string]$catalog.reference.versionHash
    generatedBy = 'tools/extract-noita-pixel-scene-visuals.ps1'
    assetCount = $visuals.Count
    assets = $visuals
}
[IO.File]::WriteAllText(
    [IO.Path]::GetFullPath($ProvenancePath),
    ($provenance | ConvertTo-Json -Depth 10) + "`n",
    $utf8NoBom)

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('using PixelEngine.Hosting;')
$lines.Add('using PixelEngine.Scripting;')
$lines.Add('')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaPixelSceneVisualCatalog')
$lines.Add('{')
$lines.Add('    private static readonly NoitaPixelSceneVisualDefinition[] LayerValues =')
$lines.Add('    [')
foreach ($visual in $visuals) {
    $layer = if ($visual.kind -eq 'background') { 'WorldVisualLayerKind.Background' } else { 'WorldVisualLayerKind.Decoration' }
    $assetId = "noita-global-scene-$($visual.ordinal)-$($visual.kind)"
    $lines.Add(('        new(new ScriptAssetReference(ScriptAssetKind.Texture, "{0}", "{1}"), {2}, {3}, {4}, {5}, {6}, "{7}", "{8}"),' -f
        $assetId, $visual.contentPath, $visual.worldX, $visual.worldY, $visual.width, $visual.height,
        $layer, $visual.sourcePath, $visual.sourceSha256))
}
$lines.Add('    ];')
$lines.Add('')
$lines.Add('    internal static ReadOnlySpan<NoitaPixelSceneVisualDefinition> Layers => LayerValues;')
$lines.Add('}')
[IO.File]::WriteAllText([IO.Path]::GetFullPath($GeneratedCodePath), ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host "Extracted $($visuals.Count) Noita pixel scene visual layers."
