[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $DataRoot,

    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),

    [string] $OutputPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaPixelSceneMarkers.Generated.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$utf8NoBom = [Text.UTF8Encoding]::new($false)
$resolvedDataRoot = (Resolve-Path -LiteralPath $DataRoot).Path
$catalog = Get-Content -Raw -LiteralPath $CatalogPath | ConvertFrom-Json -Depth 30
[xml]$materialsXml = [IO.File]::ReadAllText((Join-Path $resolvedDataRoot 'materials.xml'))

function Normalize-Rgb([string] $Value) {
    $normalized = $Value.Trim().Replace('0x', '').ToLowerInvariant()
    if ($normalized.Length -eq 8) { return $normalized.Substring(2) }
    if ($normalized.Length -eq 6) { return $normalized }
    throw "Invalid color '$Value'."
}

function Escape-CSharp([string] $Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$materialColors = @{}
foreach ($material in $materialsXml.SelectNodes('//*[@name and @wang_color]')) {
    $materialColors[(Normalize-Rgb ([string]$material.wang_color))] = $true
    foreach ($graphics in $material.SelectNodes('.//Graphics[@color]')) {
        $materialColors[(Normalize-Rgb ([string]$graphics.color))] = $true
    }
}

$registrations = @{}
$biomeScriptRoot = Join-Path $resolvedDataRoot 'scripts\biomes'
foreach ($file in Get-ChildItem -LiteralPath $biomeScriptRoot -Filter '*.lua' -Recurse -File) {
    $relativePath = 'data/' + [IO.Path]::GetRelativePath($resolvedDataRoot, $file.FullName).Replace('\', '/')
    foreach ($line in [IO.File]::ReadLines($file.FullName)) {
        if ($line -notmatch '^\s*RegisterSpawnFunction\(\s*0x([0-9A-Fa-f]{8})\s*,\s*"([^"]+)"') {
            continue
        }

        $color = $Matches[1].ToLowerInvariant()
        if (-not $registrations.ContainsKey($color)) {
            $registrations[$color] = [Collections.Generic.List[object]]::new()
        }

        $registrations[$color].Add([pscustomobject]@{
            Function = $Matches[2]
            SourcePath = $relativePath
        })
    }
}

$markers = [Collections.Generic.List[object]]::new()
$scenes = @($catalog.globalPixelScenes.bufferedScenes)
for ($sceneIndex = 0; $sceneIndex -lt $scenes.Count; $sceneIndex++) {
    $scene = $scenes[$sceneIndex]
    if ($null -eq $scene.assets.material) { continue }

    $sourcePath = [string]$scene.assets.material.path
    $sourceFile = Join-Path $resolvedDataRoot $sourcePath.Substring(5)
    $bitmap = [Drawing.Bitmap]::new($sourceFile)
    try {
        for ($y = 0; $y -lt $bitmap.Height; $y++) {
            for ($x = 0; $x -lt $bitmap.Width; $x++) {
                $pixel = $bitmap.GetPixel($x, $y)
                if ($pixel.A -eq 0) { continue }
                $rgb = '{0:x2}{1:x2}{2:x2}' -f $pixel.R, $pixel.G, $pixel.B
                if ($materialColors.ContainsKey($rgb)) { continue }

                $argb = '{0:x2}{1:x2}{2:x2}{3:x2}' -f $pixel.A, $pixel.R, $pixel.G, $pixel.B
                $matching = if ($registrations.ContainsKey($argb)) { @($registrations[$argb]) } else { @() }
                $functions = @($matching | ForEach-Object Function | Sort-Object -Unique)
                $sources = @($matching | ForEach-Object SourcePath | Sort-Object -Unique)
                $function = if ($functions.Count -eq 1) { $functions[0] } else { "builtin-or-unresolved:$argb" }
                $origin = if ($sources.Count -gt 0) { [string]::Join('|', $sources) } else { $sourcePath }
                $markers.Add([pscustomobject]@{
                    SceneOrdinal = $sceneIndex
                    LocalX = $x
                    LocalY = $y
                    WorldX = [int]$scene.pos_x + $x
                    WorldY = [int]$scene.pos_y + $y
                    Color = $argb
                    Function = $function
                    Origin = $origin
                })
            }
        }
    }
    finally {
        $bitmap.Dispose()
    }
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaPixelSceneCatalog')
$lines.Add('{')
$lines.Add('    private static readonly NoitaPixelSceneMarkerDefinition[] MarkerValues =')
$lines.Add('    [')
foreach ($marker in $markers) {
    $lines.Add(('        new({0}, {1}, {2}, {3}L, {4}L, "{5}", "{6}", "{7}"),' -f
        $marker.SceneOrdinal,
        $marker.LocalX,
        $marker.LocalY,
        $marker.WorldX,
        $marker.WorldY,
        (Escape-CSharp $marker.Color),
        (Escape-CSharp $marker.Function),
        (Escape-CSharp $marker.Origin)))
}
$lines.Add('    ];')
$lines.Add('')
$lines.Add('    internal static ReadOnlySpan<NoitaPixelSceneMarkerDefinition> Markers => MarkerValues;')
$lines.Add('}')

[IO.File]::WriteAllLines([IO.Path]::GetFullPath($OutputPath), $lines, $utf8NoBom)
Write-Output "Generated $($markers.Count) global Pixel Scene markers at '$OutputPath'."
