[CmdletBinding()]
param(
    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaPixelScenes.Generated.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8NoBom = [Text.UTF8Encoding]::new($false)
$catalog = Get-Content -Raw -LiteralPath $CatalogPath | ConvertFrom-Json -Depth 30

function Quote([string] $Value) {
    if ([string]::IsNullOrEmpty($Value)) { return 'string.Empty' }
    return '"' + $Value.Replace('\\', '\\\\').Replace('"', '\"') + '"'
}

function Value-OrEmpty($Object, [string] $Name) {
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { return '' }
    return [string]$property.Value
}

function Asset-Value($Scene, [string] $Name, [string] $Property, $Fallback) {
    $asset = $Scene.assets.PSObject.Properties[$Name].Value
    if ($null -eq $asset) { return $Fallback }
    $value = $asset.PSObject.Properties[$Property]
    if ($null -eq $value) { return $Fallback }
    return $value.Value
}

$bufferedSceneCount = @($catalog.globalPixelScenes.bufferedScenes).Count
$scenes = @($catalog.globalPixelScenes.bufferedScenes) + @($catalog.globalPixelScenes.splicedScenes)
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaPixelSceneCatalog')
$lines.Add('{')
$lines.Add("    internal const int SceneCount = $($scenes.Count);")
$lines.Add('')
$lines.Add('    private static readonly NoitaPixelSceneDefinition[] SceneValues =')
$lines.Add('    [')
for ($i = 0; $i -lt $scenes.Count; $i++) {
    $scene = $scenes[$i]
    $material = Value-OrEmpty $scene 'material_filename'
    $colors = Value-OrEmpty $scene 'colors_filename'
    $background = Value-OrEmpty $scene 'background_filename'
    $x = [int](Value-OrEmpty $scene 'pos_x')
    $y = [int](Value-OrEmpty $scene 'pos_y')
    $clean = (Value-OrEmpty $scene 'clean_area_before') -eq '1'
    $skipBiome = (Value-OrEmpty $scene 'skip_biome_checks') -eq '1'
    $skipEdges = (Value-OrEmpty $scene 'skip_edge_textures') -eq '1'
    $width = [int](Asset-Value $scene 'material' 'width' 0)
    $height = [int](Asset-Value $scene 'material' 'height' 0)
    if ($width -eq 0) { $width = [int](Asset-Value $scene 'colors' 'width' 0) }
    if ($height -eq 0) { $height = [int](Asset-Value $scene 'colors' 'height' 0) }
    if ($width -eq 0) { $width = [int](Asset-Value $scene 'background' 'width' 0) }
    if ($height -eq 0) { $height = [int](Asset-Value $scene 'background' 'height' 0) }
    $materialSha = [string](Asset-Value $scene 'material' 'sha256' '')
    $colorsSha = [string](Asset-Value $scene 'colors' 'sha256' '')
    $backgroundSha = [string](Asset-Value $scene 'background' 'sha256' '')
    $stableId = $(if ($i -lt $bufferedSceneCount) { "global-buffered-$i" } else { "global-spliced-$($i - $bufferedSceneCount)" })
    $lines.Add(('        new({0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}, {10}, {11}, {12}, {13}, {14}),' -f
        $i, $x, $y, $width, $height,
        (Quote $material), (Quote $colors), (Quote $background),
        (Quote $materialSha), (Quote $colorsSha), (Quote $backgroundSha),
        $clean.ToString().ToLowerInvariant(), $skipBiome.ToString().ToLowerInvariant(),
        $skipEdges.ToString().ToLowerInvariant(), (Quote $stableId)))
}
$lines.Add('    ];')
$lines.Add('')
$lines.Add('    internal static ReadOnlySpan<NoitaPixelSceneDefinition> Scenes => SceneValues;')
$lines.Add('}')

$resolvedOutput = [IO.Path]::GetFullPath($OutputPath)
[IO.File]::WriteAllText($resolvedOutput, ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host "Generated $($scenes.Count) pure C# Noita pixel scene definitions."
