[CmdletBinding()]
param(
    [string] $WorldCatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaBiomeMaterialCatalog.Generated.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$catalog = Get-Content -LiteralPath $WorldCatalogPath -Raw | ConvertFrom-Json -Depth 40
$culture = [Globalization.CultureInfo]::InvariantCulture
$lines = [Collections.Generic.List[string]]::new()

function Escape-CSharp([string] $Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

function Read-Value($Object, [string] $Name, $DefaultValue) {
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property -or [string]::IsNullOrWhiteSpace([string]$property.Value)) {
        return $DefaultValue
    }

    return $property.Value
}

function Format-Bool($Object, [string] $Name, [bool] $DefaultValue = $false) {
    $value = [string](Read-Value $Object $Name $(if ($DefaultValue) { '1' } else { '0' }))
    return $(if ($value -eq '1' -or $value.Equals('true', [StringComparison]::OrdinalIgnoreCase)) { 'true' } else { 'false' })
}

function Format-Double($Object, [string] $Name, [double] $DefaultValue = 0) {
    $value = [double]::Parse([string](Read-Value $Object $Name $DefaultValue), $culture)
    return $value.ToString('R', $culture)
}

function Format-Int($Object, [string] $Name, [int] $DefaultValue = 0) {
    return [int](Read-Value $Object $Name $DefaultValue)
}

$lines.Add('// <auto-generated />')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaBiomeMaterialCatalog')
$lines.Add('{')
$lines.Add('    private static readonly NoitaBiomeMaterialProfile[] ProfileValues =')
$lines.Add('    [')

foreach ($biome in $catalog.biomes) {
    $layers = @($biome.materialLayers)
    $lines.Add(('        new NoitaBiomeMaterialProfile("{0}", "{1}",' -f
        (Escape-CSharp ([string]$biome.id)),
        (Escape-CSharp ([string]$biome.sourcePath))))
    $lines.Add('        [')
    foreach ($layer in $layers) {
        $lines.Add('            new NoitaWangMaterialLayerDefinition')
        $lines.Add('            {')
        $lines.Add("                Enabled = $(Format-Bool $layer '_enabled' $true),")
        $lines.Add("                AddPerlin = $(Format-Double $layer 'add_perlin'),")
        $lines.Add("                AddPerlinScaleX = $(Format-Double $layer 'add_perlin_scale_x' 0.01),")
        $lines.Add("                AddPerlinScaleY = $(Format-Double $layer 'add_perlin_scale_y' 0.01),")
        $lines.Add("                IsPolygon = $(Format-Bool $layer 'is_polygon'),")
        $lines.Add("                IsRare = $(Format-Bool $layer 'is_rare'),")
        $lines.Add("                LimitMaxY = $(Format-Double $layer 'limit_max_y'),")
        $lines.Add("                LimitMinY = $(Format-Double $layer 'limit_min_y'),")
        $lines.Add("                LimitY = $(Format-Bool $layer 'limit_y'),")
        $lines.Add("                MaterialIndex = $(Format-Int $layer 'material_index' 10),")
        $lines.Add("                MaterialMax = $(Format-Double $layer 'material_max' 1),")
        $lines.Add("                MaterialMin = $(Format-Double $layer 'material_min'),")
        $lines.Add(('                MaterialName = "{0}",' -f (Escape-CSharp ([string]$layer.material_name))))
        $lines.Add("                RarePolkaIsBoxed = $(Format-Bool $layer 'rare_polka_is_boxed'),")
        $lines.Add("                RarePolkaProbability = $(Format-Double $layer 'rare_polka_probability'),")
        $lines.Add("                RarePolkaRadiusHigh = $(Format-Double $layer 'rare_polka_radius_high'),")
        $lines.Add("                RarePolkaRadiusLow = $(Format-Double $layer 'rare_polka_radius_low'),")
        $lines.Add("                RareRequiredMax = $(Format-Double $layer 'rare_required_max'),")
        $lines.Add("                RareRequiredMin = $(Format-Double $layer 'rare_required_min'),")
        $lines.Add("                RareScaleX = $(Format-Double $layer 'rare_scale_x'),")
        $lines.Add("                RareScaleY = $(Format-Double $layer 'rare_scale_y'),")
        $lines.Add("                RareUsePerlin = $(Format-Bool $layer 'rare_use_perlin'),")
        $lines.Add("                RareUsePolka = $(Format-Bool $layer 'rare_use_polka'),")
        $lines.Add('            },')
    }
    $lines.Add('        ]),')
}

$lines.Add('    ];')
$lines.Add('}')

$text = [string]::Join("`n", $lines) + "`n"
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), $text, [Text.UTF8Encoding]::new($false))
Write-Output "Wrote $OutputPath with $($catalog.biomes.Count) biome profiles and $($catalog.statistics.materialLayers) layers."
