[CmdletBinding()]
param(
    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaMarkerRules.Generated.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8NoBom = [Text.UTF8Encoding]::new($false)
$catalog = Get-Content -Raw -LiteralPath $CatalogPath | ConvertFrom-Json -Depth 30

function Resolve-Kind([string] $Function) {
    if ($Function -match 'vine|fung|tree|root|grass|plant|bush|nest|hanger') {
        return 'Vegetation'
    }
    if ($Function -match 'chest|shop|item|wand|potion|treasure|reward|prize|book|bottle|brimstone|fruit|egg|perk') {
        return 'Loot'
    }
    if ($Function -match 'enemies|enemy|robots|scavenger|fish|animal|alchemist|crawler|scorpion|friend|shopkeeper|cook|killer') {
        return 'Encounter'
    }
    if ($Function -match 'trigger|check|teleport|portal|checkpoint|finish|pressureplate|receptacle|target|gate|door|puzzle|hourglass') {
        return 'Trigger'
    }
    if ($Function -match 'acid|oil|gunpowder|laser|lamp|turret|machine|pipe|tank|trap|apparatus|forcefield|physics|prop|crate|barrel|chair|table|rock|rubble|stone|statue|wheel|cart|corpse|skull|bone') {
        return 'Prop'
    }
    if ($Function -match '^load_|pixel_scene|structure|background|beam|panel|pillar|pod|room|altar|building|catwalk|bridge|bunker|forge') {
        return 'PixelScene'
    }
    return 'Effect'
}

$occurrences = @{}
$biomes = @{}
foreach ($biome in $catalog.biomes) {
    if ($null -eq $biome.lua) {
        continue
    }
    foreach ($spawn in $biome.lua.spawnFunctions) {
        $function = [string]$spawn.function
        if ([string]::IsNullOrWhiteSpace($function)) {
            continue
        }
        $occurrences[$function] = 1 + [int]($occurrences[$function] ?? 0)
        if (-not $biomes.ContainsKey($function)) {
            $biomes[$function] = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
        }
        [void]$biomes[$function].Add([string]$biome.id)
    }
}

$functions = @($occurrences.Keys | Sort-Object)
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaMarkerRuleCatalog')
$lines.Add('{')
$lines.Add("    internal const int SourceRegistrationCount = $(@($occurrences.Values | Measure-Object -Sum).Sum);")
$lines.Add("    internal const int UniqueRuleCount = $($functions.Count);")
$lines.Add('')
$lines.Add('    internal static bool TryResolveGenerated(string function, out NoitaMarkerRule rule)')
$lines.Add('    {')
$lines.Add('        rule = function switch')
$lines.Add('        {')
foreach ($function in $functions) {
    $escaped = $function.Replace('\\', '\\\\').Replace('"', '\"')
    $kind = Resolve-Kind $function
    $sourceCount = [int]$occurrences[$function]
    $biomeCount = $biomes[$function].Count
    $lines.Add(('            "{0}" => new("{0}", NoitaMarkerRuleKind.{1}, {2}, {3}),' -f $escaped, $kind, $sourceCount, $biomeCount))
}
$lines.Add('            _ => default,')
$lines.Add('        };')
$lines.Add('        return !string.IsNullOrEmpty(rule.Function);')
$lines.Add('    }')
$lines.Add('}')

$resolvedOutput = [IO.Path]::GetFullPath($OutputPath)
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $resolvedOutput) | Out-Null
[IO.File]::WriteAllText($resolvedOutput, ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host "Generated $($functions.Count) pure C# Noita marker rules from $(@($occurrences.Values | Measure-Object -Sum).Sum) source registrations."
