[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $DataRoot,

    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\content\noita-world-content.json'),

    [string] $OutputPath = (Join-Path $PSScriptRoot '..\demo\PixelEngine.Demo\scripts\NoitaPixelSceneMasks.Generated.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$utf8NoBom = [Text.UTF8Encoding]::new($false)
$resolvedDataRoot = (Resolve-Path -LiteralPath $DataRoot).Path
$catalog = Get-Content -Raw -LiteralPath $CatalogPath | ConvertFrom-Json -Depth 30
[xml]$materialsXml = [IO.File]::ReadAllText((Join-Path $resolvedDataRoot 'materials.xml'))

function Normalize-Color([string] $Value) {
    $normalized = $Value.Trim().Replace('0x', '').ToLowerInvariant()
    if ($normalized.Length -eq 6) { return $normalized }
    if ($normalized.Length -eq 8) { return $normalized.Substring(2) }
    throw "Invalid material color '$Value'."
}

function Add-Alias([hashtable] $Aliases, [string] $Color, [string] $Name, [int] $Priority) {
    if ([string]::IsNullOrWhiteSpace($Color)) { return }
    $key = Normalize-Color $Color
    if (-not $Aliases.ContainsKey($key) -or $Priority -gt $Aliases[$key].Priority) {
        $Aliases[$key] = [pscustomobject]@{ Name = $Name; Priority = $Priority }
    }
}

function Resolve-MaterialCode([string] $Name) {
    $value = $Name.ToLowerInvariant()
    if ($value -match 'air|void') { return 0 }
    if ($value -match '^water') { return 3 }
    if ($value -match 'steel|metal') { return 5 }
    if ($value -match 'wood') { return 6 }
    if ($value -match 'templebrick') { return 8 }
    if ($value -match 'glowstone|crystal') { return 9 }
    if ($value -match 'cloud|smoke') { return 10 }
    if ($value -match '^ice') { return 11 }
    if ($value -eq 'snow') { return 12 }
    if ($value -match 'snow_static|sand_static') { return 7 }
    if ($value -match 'soil|grass') { return 1 }
    if ($value -match 'rock|sandstone|snowrock') { return 4 }
    if ($value -match 'trailer_text|glass') { return 13 }
    throw "No Demo material mapping for Noita material '$Name'."
}

function Compress-Brotli([byte[]] $Bytes) {
    $output = [IO.MemoryStream]::new()
    try {
        $brotli = [IO.Compression.BrotliStream]::new($output, [IO.Compression.CompressionLevel]::Optimal, $true)
        try { $brotli.Write($Bytes, 0, $Bytes.Length) }
        finally { $brotli.Dispose() }
        return $output.ToArray()
    }
    finally { $output.Dispose() }
}

$aliases = @{}
foreach ($material in $materialsXml.SelectNodes('//*[@name and @wang_color]')) {
    $name = [string]$material.name
    Add-Alias $aliases ([string]$material.wang_color) $name 2
    foreach ($graphics in $material.SelectNodes('.//Graphics[@color]')) {
        Add-Alias $aliases ([string]$graphics.color) $name 1
    }
}

$definitions = [Collections.Generic.List[object]]::new()
$bufferedScenes = @($catalog.globalPixelScenes.bufferedScenes)
for ($sceneIndex = 0; $sceneIndex -lt $bufferedScenes.Count; $sceneIndex++) {
    $scene = $bufferedScenes[$sceneIndex]
    if ($null -eq $scene.assets.material) { continue }
    $sourcePath = [string]$scene.material_filename
    $sourceFile = Join-Path $resolvedDataRoot $sourcePath.Substring(5)
    $bitmap = [Drawing.Bitmap]::new($sourceFile)
    try {
        $pixels = [byte[]]::new($bitmap.Width * $bitmap.Height)
        $markerCount = 0
        for ($y = 0; $y -lt $bitmap.Height; $y++) {
            for ($x = 0; $x -lt $bitmap.Width; $x++) {
                $color = $bitmap.GetPixel($x, $y)
                if ($color.A -eq 0) { continue }
                $rgb = '{0:x2}{1:x2}{2:x2}' -f $color.R, $color.G, $color.B
                if (-not $aliases.ContainsKey($rgb)) {
                    $markerCount++
                    continue
                }
                $pixels[($y * $bitmap.Width) + $x] = [byte](Resolve-MaterialCode $aliases[$rgb].Name)
            }
        }

        $compressed = Compress-Brotli $pixels
        $definitions.Add([pscustomobject]@{
            Ordinal = $sceneIndex
            Width = $bitmap.Width
            Height = $bitmap.Height
            MarkerCount = $markerCount
            DecodedSha256 = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($pixels)).ToLowerInvariant()
            Data = [Convert]::ToBase64String($compressed)
        })
    }
    finally { $bitmap.Dispose() }
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace PixelEngine.Demo;')
$lines.Add('')
$lines.Add('internal static partial class NoitaPixelSceneCatalog')
$lines.Add('{')
$lines.Add('    private static readonly NoitaPixelSceneMaskDefinition[] MaskValues =')
$lines.Add('    [')
foreach ($definition in $definitions) {
    $lines.Add(('        new({0}, {1}, {2}, {3}, "{4}", "{5}"),' -f
        $definition.Ordinal, $definition.Width, $definition.Height, $definition.MarkerCount,
        $definition.DecodedSha256, $definition.Data))
}
$lines.Add('    ];')
$lines.Add('')
$lines.Add('    internal static ReadOnlySpan<NoitaPixelSceneMaskDefinition> Masks => MaskValues;')
$lines.Add('}')

[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host "Generated $($definitions.Count) Noita pixel scene material masks."
